### ISSUE TITLE
Move to GitHub actions

### ISSUE THREAD

**Issue by hinerm** [fiji/fiji-builds#5]
The Travis CI cache is broken. It does not recognize that a cache exists and thus does not allow clearing it.

**Comment by hinerm** [comment]
@ctrueden I have temporarily turned off `Travis CI` build-on-push and also its daily cron job on `master`. The `cache` problem is ridiculous - I thought that building without a cache would clear the old cache. I was wrong! So when I turn caching off it pulls in the correct JDK.. but when I turn caching back on, the old JDK pops up again and the bundle with the desired JDK is lost.

Some interim options:
1. We could turn caching off and the cron job back on, and just pay the bandwidth cost of downloading all the JDKs daily.
1. We could change the cache directory each time we update the JDK.

**Comment by hinerm** [comment]
I just noticed that 32-bit windows/linux bundles were missing in the latest archive.

I assume the cache may also be relied upon to maintain un-updated bundles. I manually copied the previous build's 32-bit bundles to the latest archive for now.

**Comment by ctrueden** [comment]
Wow. Sorry for your pain, @hinerm. I'm on board with switching this repository over to GitHub Actions. With the recent announcement of [pricing changes on Travis](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) which impact macOS builds in particular, we'll probably need to start migrating away from Travis anyway soon, at least for cross-platform builds, which includes this one (see #1).

**Comment by ctrueden** [comment]
Addressed in 71f77d9367bcade6a01dac56cabc1090e3981ced.
